{
 "title": "Sui Bridge - Indexer",
 "tags": [
  "Validator",
  "Sui"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values({blockchain=\"sui\", node_type=\"bridge-indexer\"},network)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values({blockchain=\"sui\", network=\"$network\", node_type=\"bridge-indexer\"},hostname)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checkpoint ingestion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "data_ingestion_checkpoint{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Total number of eth bridge transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_eth_bridge_transactions{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eth vault balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_eth_vault_balance{node_type = \"bridge-indexer\",hostname=\"$hostname\"} / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of eth token deposited transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_eth_token_deposited{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of sui bridge transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_sui_bridge_transactions{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest retrieved checkpoint for each task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "bridge_indexer_tasks_latest_retrieved_checkpoints{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{task_name}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "The remaining checkpoints for the currently running backfill task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "bridge_indexer_backfill_tasks_remaining_checkpoints{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of inflight live tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "bridge_indexer_inflight_live_tasks{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Total processed checkpoints for each task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "bridge_indexer_tasks_processed_checkpoints{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{task_name}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Inflight items in channels.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "monitored_channel_inflight{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of running tasks per callsite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "monitored_tasks{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{callsite}}"
    }
   ]
  },
  {
   "title": "The latest synced eth blocks synced for each contract",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "bridge_last_synced_eth_blocks{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{contract_address}}"
    }
   ]
  },
  { "title": "ETH RPCs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "ETH RPC Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "bridge_eth_rpc_queries{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ETH RPC Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(bridge_eth_rpc_queries{node_type = \"bridge-indexer\", hostname=\"$hostname\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ETH RPC Median Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(bridge_eth_rpc_queries_latency_bucket{node_type=\"bridge-indexer\",hostname=\"$hostname\"}[5m])) by (le, type))\n\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "The latest finalized eth block observed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_last_finalized_eth_block{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Total number of sui token deposited transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_sui_token_deposited{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of other sui bridge transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_sui_bridge_txn_other{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of sui token approved transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_sui_token_transfer_approved{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of sui token claimed transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_indexer_total_sui_token_transfer_claimed{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of unrecognized events in sui watcher",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_sui_watcher_unrecognized_events{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "Successful Requests"
    }
   ]
  },
  {
   "title": "Total number of received events in sui watcher",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_sui_watcher_received_events{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "Successful Requests"
    }
   ]
  },
  {
   "title": "Whether the sui bridge is paused",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_sui_bridge_paused{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "Inflight Requests"
    }
   ]
  },
  {
   "title": "Total number of received actions in sui watcher",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_sui_watcher_received_actions{node_type = \"bridge-indexer\",hostname=\"$hostname\"}",
     "legendFormat": "Cache Misses"
    }
   ]
  }
 ]
}